name: Dev Envirement

on:
    workflow_dispatch:
    push:
        branches:
            - dev


jobs:
  # build-and-push-docker-image:
  #   runs-on: ubuntu-latest

  #   services:
  #     redis:
  #       image: redis/redis-stack:latest
  #       ports:
  #         - 6379:6379

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}  # Add Docker Hub username as a secret
  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}  # Add Docker Hub password as a secret

  #     - name: Build and push Docker images
  #       run: |
  #         docker build \
  #         --build-arg MONGO_URI="${{ secrets.MONGO_URI }}" \
  #         --build-arg SCRAPING_URI="${{ secrets.SCRAPING_URI }}" \
  #         -t ${{ secrets.DOCKERHUB_USERNAME }}/tuntransport-dashboard:latest Dashboard/.

  #         docker build \
  #         --build-arg MONGO_URI="${{ secrets.MONGO_URI }}" \
  #         -t ${{ secrets.DOCKERHUB_USERNAME }}/tuntransport-data-ingestion:latest Data-Ingestion/.

  #         docker push ${{ secrets.DOCKERHUB_USERNAME }}/tuntransport-dashboard:latest
  #         docker push ${{ secrets.DOCKERHUB_USERNAME }}/tuntransport-data-ingestion:latest



  ssh-pull-and-run:
    runs-on: ubuntu-latest
    # needs: build-and-push-docker-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Saving SSH private key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private.key


      - name: Add SSH key to known hosts
        run: |
          ssh-keyscan -t rsa -p 22 "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts




      - name: Download compose file
        run: |
          mkdir -p ./compose
          cp ./compose.yaml ./compose/


      - name: Copy Docker Compose file to server
        run: |
          scp -i ~/.ssh/private.key -P 22 ./compose/compose.yaml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/.

      - name: Run Docker Compose
        run: |
          ssh -i ~/.ssh/private.key -p 22 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /. && docker compose up -d"
